# Site settings
title: anthernet
description: >
  coding resources // decentralized solutions // digital freedom

# Jekyll-FTP
# username:
# server_url:
# remote_dir:

# Baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://anthernet.com" # the base hostname & protocol for your site
permalink: "/blog/:title/"
author:
  github: tonyynot
  twitter: tonecodes
  # disqus: 
  # instagram: blankwaves
  # linkedin:

google_analytics: 'UA-60032993-2'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygments
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Staticman (comments generator)
allowedFields: ['name', 'email', 'comment']
branch: 'gh-pages'
format: 'yaml'
moderation: true
path: _data/posts/{options.post-slug}
requiredFields: ['name', 'comment']
transforms:
  email: 'md5'

plugins_dir:
  - jekyll-gist
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - font-awesome-sass
